### ISSUE TITLE
Remediate security vulnerabilities

### ISSUE THREAD

**Issue by spartanhooah** [tomtom-international/goji-http-client#118]
I am using version 3.1.0, and our security software (jFrog's Xray) is flagging transitive dependencies. So far I've encountered
* `org.apache.maven:maven-settings:3.1.1` - fixed as of 3.2.1
* `dom4j:dom4j:1.1` - fixed as of `org.dom4j:dom4j:2.1.3`
* `commons-beanutils:commons-beanutils:1.7.0` - fixes as of 1.9.4

I think if the group `org.codehaus.mojo` is removed from the dependencies, all these security vulnerabilities will be resolved.

**Comment by artamonovkirill** [comment]
Hi, @spartanhooah.
Thanks for raising this.
I've removed the version plugin.
@sanderdeneve-tomtom would you be able to create a release, please?

**Comment by artamonovkirill** [comment]
@spartanhooah 3.1.1 has been released, can you please give it a try?

**Comment by spartanhooah** [comment]
Yup, that fixed all the vulnerabilities our scanners were finding, and everything still works. Thanks!
