### ISSUE TITLE
Add default content type header?

### ISSUE THREAD

**Issue by spartanhooah** [tomtom-international/goji-http-client#120]
Currently I have to add a content-type header to all requests. Is there a way to set a default one? I tried adding a headers map to the HttpClient constructor, but it didn't seem to propagate; I kept getting 415s.

**Comment by artamonovkirill** [comment]
Hi, @spartanhooah.
Thanks for reporting this.
No, default headers aren't supported at the moment.
I'll take a look into adding this later this week.

**Comment by artamonovkirill** [comment]
Added: https://github.com/tomtom-international/goji-http-client/blob/main/README.md#default-headers
@sanderdeneve-tomtom can you please create a 3.2.0 release? 🙏

**Comment by pavelbrylov** [comment]
@sanderdeneve-tomtom any chance of making 3.2.0 soon?

**Comment by artamonovkirill** [comment]
Maybe @rijnb can help? 🙏

**Comment by RijnBuve-TomTom** [comment]
Done - next time just ping me on Slack please.
