### ISSUE TITLE
Incorrect deserialization of numerical value

### ISSUE THREAD

**Issue by spartanhooah** [tomtom-international/goji-http-client#202]
We're calling an API that returns JSON and has a numeric value of e.g. `10.00`. This gets deserialized into a `Double`  of  `10.0`. IMO this should be deserialized into a `BigDecimal` instead to maintain the proper precision.

**Comment by artamonovkirill** [comment]
Hi, @spartanhooah 👋 
Thanks for raising that.
Can you share some examples of how you deserialize the values in your tests?
I've added a few tests for a generic `Map` and a dedicated `Info` classes: https://github.com/tomtom-international/goji-http-client/pull/203.
Jackson-databind might default to Double when deserializing generic objects (like `Map`).
I'll dig deeper to verify that and check if that can be configured in the object mapper.

**Comment by artamonovkirill** [comment]
Indeed, `USE_BIG_DECIMAL_FOR_FLOATS ` is one of the Jackson-databind features: https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features#type-conversions

You can do something like for your setup:
```
        def mapper = new ObjectMapper().enable(USE_BIG_DECIMAL_FOR_FLOATS)
        def http = new HttpClient(mapper: mapper)
```

**Comment by spartanhooah** [comment]
Ah, I didn't know we could pass an `ObjectMapper` to the `HttpClient`. That sounds like it'll work perfectly. Let me test it out.

**Comment by spartanhooah** [comment]
That does the trick. Thank you.
