### ISSUE TITLE
How to add query parameters?

### ISSUE THREAD

**Issue by spartanhooah** [tomtom-international/goji-http-client#79]
I couldn't find anything in the readme or API documentation about adding query parameters to requests. I can append them to the `path` parameter, but a separate handling of query parameters would be really nice.

**Comment by artamonovkirill** [comment]
Hi, @spartanhooah.
There's no dedicated section regarding query params, but there are a few examples, e.g. in the [intro](https://github.com/tomtom-international/goji-http-client#intro).
I'll have a look into supporting query params via a map.

**Comment by spartanhooah** [comment]
Great, thanks for the quick response. Now to await Spock 2.2 stable!

**Comment by artamonovkirill** [comment]
[3.1.0 release](https://search.maven.org/artifact/com.tomtom.http/goji-http-client/3.1.0/jar) is out 🙌
